apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  ports:
    - name: {{ .Values.portName }}
      port: 8080
      targetPort: {{ .Values.portName }}
      protocol: TCP
  selector:
    {{- include "my-app.selectorLabels" . | nindent 4 }}
