apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "my-app.fullname" . }}
  namespace: monitoring
  labels:
  {{- include "my-app.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: {{ .Values.portName }}
      interval: 15s
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      {{- include "my-app.labels" . | nindent 6 }}
