codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "80...100"

  status:
    project: true
    patch:
      default:
        target: 85%
        threshold: 5%