version: "3.9"
services:
  app:
    build: ../.
    ports:
      - "8080:8080"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: my.app
  fluentd:
    build: fluentd/.
    environment:
      - "FLUENTD_CONF=fluentd.conf"
    ports:
      - "24224:24224"
  elasticsearch:
    image: elasticsearch:7.12.0
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
  kibana:
    image: kibana:7.12.0
    depends_on:
      - "elasticsearch"
    ports:
      - "5601:5601"
  prometheus:
    build: prometheus/.
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:7.5.3
    ports:
      - "3000:3000"