apiVersion: v1
kind: ReplicationController
metadata:
  name: go-demo-application
spec:
  replicas: 2
  selector:
    app: go-demo-application
  template:
    metadata:
      labels:
        app: go-demo-application
    spec:
      containers:
        - name: go-demo-application
          image: wellington31/go-demo-application:0.2
          ports:
            - name: go-app
              containerPort: 8080