# Default values for example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    memory: "8Mi"
  limits:
    memory: "64Mi"

image:
  tag: ""

portName: http

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  host: myapp.kube.devmanezinho.com
  path: "/"
