name: CD

on:
  workflow_dispatch:
    inputs:
      appVersion:
        description: 'App Version'
        required: true

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./... -covermode=atomic -coverprofile="coverage.out" -coverpkg=./... -count=1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wellington31/go-demo-application:${{github.event.inputs.appVersion}}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Helm Lint
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint ./deploy/kubernetes/my-app

      - name: Package chart
        run: helm package --version ${{github.event.inputs.appVersion}} ./deploy/kubernetes/my-app

      - name: Push chart
        run: |
          helm plugin install https://github.com/hypnoglow/helm-s3.git &&
          helm repo add my-app s3://helm-0/charts &&
          helm s3 push my-app-${{github.event.inputs.appVersion}}.tgz my-app

