name: DEPLOY

on:
  workflow_dispatch:
    inputs:
      appVersion:
        description: 'App Version'
        required: true
      environment:
        description: 'Environment (production or develop)'
        required: true
        default: 'prod'

jobs:
  deploy:
    env:
      NAMESPACE: 'default'
      ENVIRONMENT: '${{github.event.inputs.environment}}'
    runs-on: ubuntu-latest
    steps:
      - name: Validates environment
        if: ${{ env.ENVIRONMENT == 'dev' || env.ENVIRONMENT != 'prod' }}
        run: echo "ENVIRONMENT=dev" >> $GITHUB_ENV

      - name: Defines namespace
        if: ${{ env.ENVIRONMENT == 'dev' }}
        run: echo "NAMESPACE=development" >> $GITHUB_ENV

      - name: Install chart
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: |
            helm plugin install https://github.com/hypnoglow/helm-s3.git &&
            helm repo add my-app s3://helm-0/charts &&
            helm install --values ./deploy/kubernetes/my-app/${{env.ENVIRONMENT}}-values --namespace ${{env.NAMESPACE}} my-app/my-app
          kubeconfig: '${{ secrets.KUBECONFIG }}'

